### ISSUE TITLE
Game cover images not visible

### ISSUE THREAD

**Issue by BLACK4585** [MCC321-QC/eMixedNiteMC#33] opened 2024-06-15 14:54 UTC
**Describe the bug**
The game cover images are not longer visible, although all images are present in the media tab and are visible with other themes.

**To Reproduce**
1. Go to Details View

**Screenshots**
<img width="257" alt="Screenshot 2024-06-15 165234" src="https://github.com/MCC321-QC/eMixedNiteMC/assets/71935902/0c72242e-dc5c-4e99-a2ba-196a8deb7e1d">

**Comment by MCC321-QC** [comment] 2024-10-14 09:04
Problem was caused by the extension [BackbroundChanger](https://github.com/darklinkpower/PlayniteExtensionsCollection?tab=readme-ov-file#extensions). Disabling the extension fixed the issue. I tried replicating the issue but could not, the extension works as intended (performance will be fixed in the near future) perhaps a wrong file or wrong config. Will close this issue.

**Closed by MCC321-QC** 2024-10-14 09:04 UTC
Labels: bug

**Comment by MCC321-QC** [comment] 2024-10-19 23:01
Ive finally been able to reproduce this problem while trying to fix performance issue with plugin [BackgroundChanger](https://github.com/darklinkpower/PlayniteExtensionsCollection?tab=readme-ov-file#extensions), the problem was in the theme and can be fixed by enabling covers function in options of [BackgroundChanger](https://github.com/darklinkpower/PlayniteExtensionsCollection?tab=readme-ov-file#extensions) or disable said plugin.

This issue is fixed in [version 3.75](https://github.com/MCC321-QC/eMixedNiteMC/commit/73751b7314770ee404a310837673ed8a91b74dae), the update will be released later today or tomorrow!
