### ISSUE TITLE
Some platform icons are missing

### ISSUE THREAD

**Issue by xCeeTee** [MCC321-QC/eMixedNiteMC#17] opened 2022-12-03 13:18 UTC
[ I'm referring to the icons such as the controller as you can see in this image.](https://i.imgur.com/3Z4tGoM.jpg) I want to have the Switch platform icon like I do with the PS and Xbox icons, but none of the Nintendo consoles are showing them.

Also, I'm noticing when looking at other people's screenshots that their platform/info banners don't overlap the covers like they do in my library. Is there some setting I've modified that may have caused this? I did a bunch of silly things when I first customized the theme but I can't seem to find the cause.

**Comment by MCC321-QC** [comment] 2023-01-08 14:40
I added Icon for all (almost) Library/Source for DuplicateHider in [v3.5](https://github.com/MCC321-QC/eMixedNiteMC/commit/e51a7105309a45481a75cb499178df2073d5815e). It should be working fine after the update.

Ill wait before closing the issue in case its not working, if everything is working as intended, let me know or close the issue.

**Comment by xCeeTee** [comment] 2023-01-09 11:37
Amazing work as always, that works perfectly. I also just realised my Game Boy games didn't have a source as well. So if somebody else finds this thread because they had a similar issue, make sure to check your source as well otherwise they'd just show the default controller icon.

**Closed** 2023-01-09 11:37 UTC
Labels: bug
